--- 
title: "jamoviリファレンス（Analysis編）"
author: "芝田 征司"
site: bookdown::bookdown_site
documentclass: ltjsbook
classoption: 12pt
biblio-style: apalike
link-citations: no
description: "本書はjamoviのAnalysisビューのリファレンスマニュアルです。"
---

```{r, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning = FALSE, fig.align = 'center', out.width='80%')
```

# はじめに {-}
本書は『心理統計法II』の授業用テキストです。毎回の授業では，テキストの理解度の確認や捕捉説明，Q&Aなどを行いながら進めていく予定です。

このテキストは相模女子大学での『心理統計法II』の授業用に公開しているもので，その他一般への公開を目的としたものではありません。このテキストの全体または一部の内容を外部に転用・公開したり，あるいはこのテキストの全体または一部に外部サイトからリンクを貼ったりすることはしないでください。また，授業レポートなどでの引用文献・参考文献として本テキストを使用することもできません。レポート等を作成する場合は，必ず専門書や論文などの資料を使用してください。

## テキストの内容 {-}
本テキストは，国内外のテキスト，専門書，論文などの資料を元に作成しています。ただし，入門用のテキストという観点から，説明については厳密さよりもわかりやすさを優先しています。そのために，専門書やその他の資料とは説明が異なる場合があるかもしれません。内容についてはできる限り正確なものになるよう努めていますが，誤りが含まれている可能性もあります。また，これは本テキストに限ったことではありませんが，作成当時は正しいとされていたことが，後の研究によって誤りとされることもありえます。本テキストの内容は，今後予告なく変更される場合があります。


## 利用の仕方 {-}
### 授業前 {-}
テキストは，授業内容1回分が1つの章になるように構成されています。毎回の授業前には，その次の回の授業範囲に該当する章を読み，理解できなかったところ，疑問に感じたことについて，授業用E-Learningサイトなどを通じて積極的に質問するようにしてください。

### 授業後 {-}
毎回の授業後にもテキストを読み直し，授業内の説明やQ&Aの内容と合わせて，理解をより深めてください。また，章末に紹介されている参考図書などを利用して，より深い知識を身につけられるようにしてください。

## その他の注意点 {-}
本テキストは，Web版の他にPDF形式でも配布しています。PDF形式は印刷用です。ページ上部のメニューからダウンロードを選択すれば使用できます。

ただし，PDF形式では動画や音声が再生できないなど一部の内容がうまく表示できません。また，Web版についても，Webブラウザによっては正常に動作しない場合があるかもしれません。